version: '3.8'

services: 
    web:
        build: .
        command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
        env_file: 
            .env
        expose: 
            - 5000
        labels: 
            - "traefik.enable=true"
            - "traefik.http.routers.amalytics.rule=Host(`amalytics.amalshaji.com`)"
            - "traefik.http.routers.amalytics.tls=true"
            - "traefik.http.routers.amalytics.tls.certresolver=letsencrypt"
    traefik:  # new
        build:
            context: .
            dockerfile: Dockerfile.traefik
        ports:
            - 80:80
            - 443:443
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik-public-certificates:/certificates"
    
volumes:
    postgres_data_prod:
    traefik-public-certificates: